{% set name = "morphodynamics" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/morphodynamics-{{ version }}.tar.gz
  sha256: f408a4bad48e39b28d3bc2bf23b5f4a8006e2720da14fa1c3c90dc5d91cb9e7f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9,<3.11
    - setuptools >=42
    - setuptools-scm >=6.0
    - wheel
  run:
    - aicsimageio
    - cmap
    - dask-core
    - dask-jobqueue
    - dill
    - ipywidgets
    - joblib
    - napari-convpaint
    - numpy
    - pandas
    - python >=3.9,<3.11
    - matplotlib-base
    - microfilm
    - scikit-image
    - tifffile
    - tqdm

test:
  imports:
    - morphodynamics
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/morphodynamics
  summary: Cell segmentation and windowing
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/guiwitz/morphodynamics

extra:
  recipe-maintainers:
    - goanpeca
